added sanity checks for update

diff --git a/update b/update
--- a/update
+++ b/update
@@ -1,6 +1,11 @@
 
 source update.conf
 
+if [ "__$RAILS_ENV" = "__" ] ; then
+   echo "rails env not found";
+   exit 1;
+end
+
 echo "using $RAILS_ENV as environment"
 RAILS_ENV=$RAILS_ENV bundle exec pumactl -P $RAILS_PATH/tmp/pids/puma.pid stop;
 RAILS_ENV=$RAILS_ENV rails resque:stop ;
