fixed birthday ordering in wp

diff --git a/update b/update
--- a/update
+++ b/update
@@ -10,23 +10,29 @@ if [ "__$RAILS_USER" = "__" ] ; then
    echo "rails user not found";
    exit 1;
 fi
+
+if [ "__$RAILS_PATH" = "__" ] ; then
+   echo "rails path not found";
+   exit 1;
+fi
+
 if [ "__$RAILS_GROUP" = "__" ] ; then
    RAILS_GROUP="$RAILS_USER"
 fi
-
+cd $RAILS_PATH
 echo "using $RAILS_ENV as environment. will chmod to $RAILS_USER:$RAILS_GROUP"
-RAILS_ENV=$RAILS_ENV bundle exec pumactl -P $RAILS_PATH/tmp/pids/puma.pid stop;
+RAILS_PATH=$RAILS_PATH RAILS_ENV=$RAILS_ENV bundle exec pumactl -P $RAILS_PATH/tmp/pids/puma.pid stop;
 RAILS_ENV=$RAILS_ENV rails resque:stop ;
 if [ "$RAILS_ENV" != "development" ] ; then
    echo "updating git to HEAD of $GIT_BRANCH" ; 
    git reset --hard HEAD ; 
    git pull origin $GIT_BRANCH ; 
+   RAILS_ENV=$RAILS_ENV bundle update ;
 fi
-RAILS_ENV=$RAILS_ENV bundle update &&
 RAILS_ENV=$RAILS_ENV rails db:migrate &&
 RAILS_ENV=$RAILS_ENV rails assets:clean assets:precompile &&
 if [ "$RAILS_ENV" != "development" ] ; then
    chown -R $RAILS_USER:$RAILS_GROUP $RAILS_PATH ;
 fi
-RAILS_ENV=$RAILS_ENV bundle exec puma &&
+RAILS_PATH=RAILS_PATH RAILS_ENV=$RAILS_ENV bundle exec puma &&
 RAILS_ENV=$RAILS_ENV rails resque:start
